"use client";

import { useState } from "react";
import Link from "next/link";

const translations = {
    id: {
        back: "← Kembali ke Kalkulator",
        pageTitle: "Syarat & Ketentuan Penggunaan",
        termsIntro: "Dengan mengakses dan menggunakan kalkulator statistik ini, Anda menyetujui ketentuan berikut:",
        term1Title: "Penggunaan Wajar:",
        term1Desc: "Situs ini disediakan untuk penggunaan manual oleh manusia. Anda dilarang keras melakukan scraping otomatis, membanjiri API kami dengan request massal (DDoS), atau melakukan rekayasa balik (reverse engineering) terhadap sistem backend kami yang dapat menyebabkan gangguan pada layanan.",
        term2Title: "Ketersediaan Layanan:",
        term2Desc: "Kami berhak penuh untuk mengubah, memperbarui, membatasi, atau menghentikan layanan kalkulator ini kapan saja tanpa pemberitahuan sebelumnya, demi menjaga stabilitas server.",
        term3Title: "Hak Kekayaan Intelektual:",
        term3Desc: "Seluruh desain antarmuka, struktur kode, dan artikel edukasi di situs ini adalah hak milik pengembang. Anda diperbolehkan membagikan tautan situs ini, namun dilarang menyalin antarmuka dan aset kami untuk tujuan komersial tanpa izin tertulis.",
        discTitle: "Penyangkalan (Disclaimer)",
        discDesc: "Kalkulator statistik yang disediakan di situs ini (termasuk namun tidak terbatas pada Uji ANOVA dan Z-Score) disediakan murni untuk tujuan edukasi, penelitian, dan referensi informasi umum. Kami tidak memberikan jaminan atas keakuratan mutlak dari hasil komputasi. Data dan hasil yang dihasilkan oleh alat ini tidak boleh dijadikan landasan tunggal untuk pengambilan keputusan medis, klaim asuransi, finansial, atau hukum yang bersifat final. Pengguna bertanggung jawab penuh atas proses validasi lanjutan, interpretasi, dan segala risiko dari penggunaan hasil perhitungan ini."
    },
    en: {
        back: "← Back to Calculator",
        pageTitle: "Terms of Service",
        termsIntro: "By accessing and using these statistical calculators, you agree to the following terms:",
        term1Title: "Fair Use:",
        term1Desc: "This site is provided for manual human use. You are strictly prohibited from automated scraping, flooding our API with mass requests, or reverse-engineering our backend systems which may disrupt the service.",
        term2Title: "Service Availability:",
        term2Desc: "We reserve the right to modify, update, limit, or discontinue this calculator service at any time without prior notice to maintain server stability.",
        term3Title: "Intellectual Property:",
        term3Desc: "All interface designs, code structures, and educational articles on this site are the property of the developer. You are encouraged to share links to our tools, but copying our interface or assets for commercial purposes without written consent is prohibited.",
        discTitle: "Disclaimer",
        discDesc: "The statistical calculators provided on this site (including but not limited to ANOVA and Z-Score Tests) are intended purely for educational, research, and general informational purposes. We make no warranties regarding the absolute accuracy of the computational results. Data and results generated by these tools must not be used as the sole basis for final medical, insurance, financial, or legal decisions. Users bear full responsibility for further validation, interpretation, and any risks associated with the use of these calculation results."
    }
};

export default function TermsAndDisclaimer() {
    const [lang, setLang] = useState<"id" | "en">("id");
    const t = translations[lang];

    return (
        <div className="p-6 md:p-12 max-w-4xl mx-auto font-sans text-gray-800">
            {/* Header dengan Navigasi dan Toggle Bahasa */}
            <div className="flex justify-between items-center mb-8 border-b pb-4">
                <Link href="/" className="text-blue-600 hover:underline font-medium">
                    {t.back}
                </Link>
                <button
                    onClick={() => setLang(lang === "id" ? "en" : "id")}
                    className="px-3 py-1.5 bg-gray-200 hover:bg-gray-300 rounded-lg text-sm font-semibold transition-colors"
                >
                    {lang === "id" ? "🇬🇧 English" : "🇮🇩 Indonesia"}
                </button>
            </div>

            {/* Bagian Terms of Service */}
            <h1 className="text-3xl font-bold mb-6">{t.pageTitle}</h1>
            <p className="mb-6 leading-relaxed text-gray-700">{t.termsIntro}</p>

            <ul className="space-y-6 list-disc pl-5 text-gray-700 mb-12">
                <li className="leading-relaxed">
                    <strong className="text-gray-900">{t.term1Title}</strong> {t.term1Desc}
                </li>
                <li className="leading-relaxed">
                    <strong className="text-gray-900">{t.term2Title}</strong> {t.term2Desc}
                </li>
                <li className="leading-relaxed">
                    <strong className="text-gray-900">{t.term3Title}</strong> {t.term3Desc}
                </li>
            </ul>

            {/* Bagian Disclaimer (Penyangkalan) */}
            <div className="bg-red-50 border border-red-100 rounded-xl p-6 md:p-8">
                <h2 className="text-2xl font-bold mb-4 text-red-800">{t.discTitle}</h2>
                <p className="leading-relaxed text-gray-800 text-justify">
                    {t.discDesc}
                </p>
            </div>
        </div>
    );
}